package edu.hnu.bgpsa.graph.framework;
public enum Signal {
	ITERATION_START, ITERATION_OVER, CHECK_STATE, CHECK_STATE_OVER, DISPATCH_OVER, COMPUTE_OVER, ITERATION_UNACTIVE, ITERATION_ACTIVE, OVER,
	MONITOR_DISPATCH_OVER,MONITOR_COMPUTE_OVER

}